# TODO. Dockerfile reference
# Dockerfile中包含了所有用于集成image的指令
# https://docs.docker.com/engine/reference/builder/#dockerfile-reference

# 使用docker可以快速构建Linux(Ubuntu发行版)测试虚拟机
FROM ubuntu:latest
LABEL authors="tongchen"

ENTRYPOINT ["top", "-b"]

# Comment
RUN echo 'we are running cool things'